name: .NET

on: [push]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core 2.2
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.*
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*
    - name: Install dependencies
      run: |
        dotnet restore FlashCap.Core/FlashCap.Core.csproj
        dotnet restore FlashCap/FlashCap.csproj
        dotnet restore FSharp.FlashCap/FSharp.FlashCap.fsproj
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore FlashCap.Core/FlashCap.Core.csproj
        dotnet build --configuration Release --no-restore FlashCap/FlashCap.csproj
        dotnet build --configuration Release --no-restore FSharp.FlashCap/FSharp.FlashCap.fsproj
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal -p:CITest=True
#      timeout-minutes: 10
